### ISSUE TITLE
Upgrading Latest Quasar (v0.17.12)

### ISSUE THREAD

**Issue by softwareishappiness** [neatpro/Laravel-Quasar#2]
Hi,

How do I upgrade to the latest Quasar? I am unsure where I need to make the necessary changes?

Thanks,
Michael

**Comment by neatpro** [comment]
### **/resources/assets/sass/app.scss**

replace
`@import url("https://unpkg.com/quasar-framework@0.15.1/dist/umd/quasar.mat.min.css");`

with
`@import url("https://cdn.jsdelivr.net/npm/quasar-framework@0.17.12/dist/umd/quasar.mat.min.css");`

### **/resources/views/welcome.blade.php**

replace
`<script src="https://unpkg.com/quasar-framework@0.15.6/dist/umd/quasar.mat.umd.min.js"></script>`

with
`<script src="https://cdn.jsdelivr.net/npm/quasar-framework@0.17.12/dist/umd/quasar.mat.umd.min.js"></script>`

**Comment by callsprout** [comment]
IntelliJ IDE indicates that I shouldn't edit this file because change will be lost when regenerated. Do you know if this will be an issue when using Laravel Mix?

**Comment by neatpro** [comment]
No issues. You are using UMD version, not part of Laravel Mix as you are calling files directly from CDN.

**Comment by callsprout** [comment]
I agree. However, the file that contains the CSS file is in a SCSS and IntelliJ is indicating that the app.scss is a "generated" file.

**Comment by neatpro** [comment]
It's not, you are using `@import`

**Comment by callsprout** [comment]
Great! Finally, could I move just the 

`<script src="https://cdn.jsdelivr.net/npm/quasar-framework@0.17.12/dist/umd/quasar.mat.umd.min.js"></script>`

to `layouts\app.blade.php` so I don't have to load it in each view. That would not be a problem do you think?

**Comment by neatpro** [comment]
You can, but you need to load it in each view, otherwise, you'll have no Quasar.

**Comment by callsprout** [comment]
Okay. Thanks so much :-)
